//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2022 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/vmware-tanzu/image-registry-operator-api/api/v1alpha2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Checksum)(nil), (*v1alpha2.Checksum)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Checksum_To_v1alpha2_Checksum(a.(*Checksum), b.(*v1alpha2.Checksum), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Checksum)(nil), (*Checksum)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Checksum_To_v1alpha1_Checksum(a.(*v1alpha2.Checksum), b.(*Checksum), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterContentLibrary)(nil), (*v1alpha2.ClusterContentLibrary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary(a.(*ClusterContentLibrary), b.(*v1alpha2.ClusterContentLibrary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ClusterContentLibrary)(nil), (*ClusterContentLibrary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary(a.(*v1alpha2.ClusterContentLibrary), b.(*ClusterContentLibrary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ClusterContentLibraryItem)(nil), (*ClusterContentLibraryItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem(a.(*v1alpha2.ClusterContentLibraryItem), b.(*ClusterContentLibraryItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterContentLibraryItemList)(nil), (*v1alpha2.ClusterContentLibraryItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterContentLibraryItemList_To_v1alpha2_ClusterContentLibraryItemList(a.(*ClusterContentLibraryItemList), b.(*v1alpha2.ClusterContentLibraryItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ClusterContentLibraryItemList)(nil), (*ClusterContentLibraryItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ClusterContentLibraryItemList_To_v1alpha1_ClusterContentLibraryItemList(a.(*v1alpha2.ClusterContentLibraryItemList), b.(*ClusterContentLibraryItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterContentLibraryList)(nil), (*v1alpha2.ClusterContentLibraryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterContentLibraryList_To_v1alpha2_ClusterContentLibraryList(a.(*ClusterContentLibraryList), b.(*v1alpha2.ClusterContentLibraryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ClusterContentLibraryList)(nil), (*ClusterContentLibraryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ClusterContentLibraryList_To_v1alpha1_ClusterContentLibraryList(a.(*v1alpha2.ClusterContentLibraryList), b.(*ClusterContentLibraryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibrary)(nil), (*v1alpha2.ContentLibrary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary(a.(*ContentLibrary), b.(*v1alpha2.ContentLibrary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibrary)(nil), (*ContentLibrary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary(a.(*v1alpha2.ContentLibrary), b.(*ContentLibrary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItem)(nil), (*ContentLibraryItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem(a.(*v1alpha2.ContentLibraryItem), b.(*ContentLibraryItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemFileUploadStatus)(nil), (*v1alpha2.ContentLibraryItemFileUploadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus(a.(*ContentLibraryItemFileUploadStatus), b.(*v1alpha2.ContentLibraryItemFileUploadStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemFileUploadStatus)(nil), (*ContentLibraryItemFileUploadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus(a.(*v1alpha2.ContentLibraryItemFileUploadStatus), b.(*ContentLibraryItemFileUploadStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemImportRequest)(nil), (*v1alpha2.ContentLibraryItemImportRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest(a.(*ContentLibraryItemImportRequest), b.(*v1alpha2.ContentLibraryItemImportRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemImportRequest)(nil), (*ContentLibraryItemImportRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest(a.(*v1alpha2.ContentLibraryItemImportRequest), b.(*ContentLibraryItemImportRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemImportRequestList)(nil), (*v1alpha2.ContentLibraryItemImportRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestList_To_v1alpha2_ContentLibraryItemImportRequestList(a.(*ContentLibraryItemImportRequestList), b.(*v1alpha2.ContentLibraryItemImportRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemImportRequestList)(nil), (*ContentLibraryItemImportRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestList_To_v1alpha1_ContentLibraryItemImportRequestList(a.(*v1alpha2.ContentLibraryItemImportRequestList), b.(*ContentLibraryItemImportRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemImportRequestSource)(nil), (*v1alpha2.ContentLibraryItemImportRequestSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource(a.(*ContentLibraryItemImportRequestSource), b.(*v1alpha2.ContentLibraryItemImportRequestSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemImportRequestSource)(nil), (*ContentLibraryItemImportRequestSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource(a.(*v1alpha2.ContentLibraryItemImportRequestSource), b.(*ContentLibraryItemImportRequestSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemImportRequestSpec)(nil), (*v1alpha2.ContentLibraryItemImportRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec(a.(*ContentLibraryItemImportRequestSpec), b.(*v1alpha2.ContentLibraryItemImportRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemImportRequestSpec)(nil), (*ContentLibraryItemImportRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec(a.(*v1alpha2.ContentLibraryItemImportRequestSpec), b.(*ContentLibraryItemImportRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemImportRequestTargetItem)(nil), (*v1alpha2.ContentLibraryItemImportRequestTargetItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem(a.(*ContentLibraryItemImportRequestTargetItem), b.(*v1alpha2.ContentLibraryItemImportRequestTargetItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemImportRequestTargetItem)(nil), (*ContentLibraryItemImportRequestTargetItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem(a.(*v1alpha2.ContentLibraryItemImportRequestTargetItem), b.(*ContentLibraryItemImportRequestTargetItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryItemList)(nil), (*v1alpha2.ContentLibraryItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemList_To_v1alpha2_ContentLibraryItemList(a.(*ContentLibraryItemList), b.(*v1alpha2.ContentLibraryItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryItemList)(nil), (*ContentLibraryItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemList_To_v1alpha1_ContentLibraryItemList(a.(*v1alpha2.ContentLibraryItemList), b.(*ContentLibraryItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContentLibraryList)(nil), (*v1alpha2.ContentLibraryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryList_To_v1alpha2_ContentLibraryList(a.(*ContentLibraryList), b.(*v1alpha2.ContentLibraryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ContentLibraryList)(nil), (*ContentLibraryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryList_To_v1alpha1_ContentLibraryList(a.(*v1alpha2.ContentLibraryList), b.(*ContentLibraryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PublishInfo)(nil), (*v1alpha2.PublishInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PublishInfo_To_v1alpha2_PublishInfo(a.(*PublishInfo), b.(*v1alpha2.PublishInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PublishInfo)(nil), (*PublishInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PublishInfo_To_v1alpha1_PublishInfo(a.(*v1alpha2.PublishInfo), b.(*PublishInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageBacking)(nil), (*v1alpha2.StorageBacking)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StorageBacking_To_v1alpha2_StorageBacking(a.(*StorageBacking), b.(*v1alpha2.StorageBacking), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.StorageBacking)(nil), (*StorageBacking)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_StorageBacking_To_v1alpha1_StorageBacking(a.(*v1alpha2.StorageBacking), b.(*StorageBacking), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubscriptionInfo)(nil), (*v1alpha2.SubscriptionInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubscriptionInfo_To_v1alpha2_SubscriptionInfo(a.(*SubscriptionInfo), b.(*v1alpha2.SubscriptionInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.SubscriptionInfo)(nil), (*SubscriptionInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SubscriptionInfo_To_v1alpha1_SubscriptionInfo(a.(*v1alpha2.SubscriptionInfo), b.(*SubscriptionInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1alpha1_Condition(a.(*v1.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BaseContentLibrarySpec)(nil), (*v1alpha2.BaseContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BaseContentLibrarySpec_To_v1alpha2_BaseContentLibrarySpec(a.(*BaseContentLibrarySpec), b.(*v1alpha2.BaseContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*CertificateVerificationInfo)(nil), (*v1alpha2.CertificateVerificationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateVerificationInfo_To_v1alpha2_CertificateVerificationInfo(a.(*CertificateVerificationInfo), b.(*v1alpha2.CertificateVerificationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ClusterContentLibraryItem)(nil), (*v1alpha2.ClusterContentLibraryItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterContentLibraryItem_To_v1alpha2_ClusterContentLibraryItem(a.(*ClusterContentLibraryItem), b.(*v1alpha2.ClusterContentLibraryItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ClusterContentLibrarySpec)(nil), (*v1alpha2.ClusterContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterContentLibrarySpec_To_v1alpha2_ClusterContentLibrarySpec(a.(*ClusterContentLibrarySpec), b.(*v1alpha2.ClusterContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_v1_Condition(a.(*Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryItemImportRequestStatus)(nil), (*v1alpha2.ContentLibraryItemImportRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestStatus_To_v1alpha2_ContentLibraryItemImportRequestStatus(a.(*ContentLibraryItemImportRequestStatus), b.(*v1alpha2.ContentLibraryItemImportRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryItemImportRequestTarget)(nil), (*v1alpha2.ContentLibraryItemImportRequestTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemImportRequestTarget_To_v1alpha2_ContentLibraryItemImportRequestTarget(a.(*ContentLibraryItemImportRequestTarget), b.(*v1alpha2.ContentLibraryItemImportRequestTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryItemSpec)(nil), (*v1alpha2.ContentLibraryItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemSpec_To_v1alpha2_ContentLibraryItemSpec(a.(*ContentLibraryItemSpec), b.(*v1alpha2.ContentLibraryItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryItemStatus)(nil), (*v1alpha2.ContentLibraryItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItemStatus_To_v1alpha2_ContentLibraryItemStatus(a.(*ContentLibraryItemStatus), b.(*v1alpha2.ContentLibraryItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryItem)(nil), (*v1alpha2.ContentLibraryItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryItem_To_v1alpha2_ContentLibraryItem(a.(*ContentLibraryItem), b.(*v1alpha2.ContentLibraryItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibrarySpec)(nil), (*v1alpha2.ContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibrarySpec_To_v1alpha2_ContentLibrarySpec(a.(*ContentLibrarySpec), b.(*v1alpha2.ContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContentLibraryStatus)(nil), (*v1alpha2.ContentLibraryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContentLibraryStatus_To_v1alpha2_ContentLibraryStatus(a.(*ContentLibraryStatus), b.(*v1alpha2.ContentLibraryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FileInfo)(nil), (*v1alpha2.FileInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileInfo_To_v1alpha2_FileInfo(a.(*FileInfo), b.(*v1alpha2.FileInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FileTransferStatus)(nil), (*v1alpha2.FileTransferStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileTransferStatus_To_v1alpha2_FileTransferStatus(a.(*FileTransferStatus), b.(*v1alpha2.FileTransferStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.BaseContentLibrarySpec)(nil), (*BaseContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BaseContentLibrarySpec_To_v1alpha1_BaseContentLibrarySpec(a.(*v1alpha2.BaseContentLibrarySpec), b.(*BaseContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.CertificateVerificationInfo)(nil), (*CertificateVerificationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CertificateVerificationInfo_To_v1alpha1_CertificateVerificationInfo(a.(*v1alpha2.CertificateVerificationInfo), b.(*CertificateVerificationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ClusterContentLibrarySpec)(nil), (*ClusterContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ClusterContentLibrarySpec_To_v1alpha1_ClusterContentLibrarySpec(a.(*v1alpha2.ClusterContentLibrarySpec), b.(*ClusterContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibraryItemImportRequestStatus)(nil), (*ContentLibraryItemImportRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestStatus_To_v1alpha1_ContentLibraryItemImportRequestStatus(a.(*v1alpha2.ContentLibraryItemImportRequestStatus), b.(*ContentLibraryItemImportRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibraryItemImportRequestTarget)(nil), (*ContentLibraryItemImportRequestTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemImportRequestTarget_To_v1alpha1_ContentLibraryItemImportRequestTarget(a.(*v1alpha2.ContentLibraryItemImportRequestTarget), b.(*ContentLibraryItemImportRequestTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibraryItemSpec)(nil), (*ContentLibraryItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemSpec_To_v1alpha1_ContentLibraryItemSpec(a.(*v1alpha2.ContentLibraryItemSpec), b.(*ContentLibraryItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibraryItemStatus)(nil), (*ContentLibraryItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryItemStatus_To_v1alpha1_ContentLibraryItemStatus(a.(*v1alpha2.ContentLibraryItemStatus), b.(*ContentLibraryItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibrarySpec)(nil), (*ContentLibrarySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibrarySpec_To_v1alpha1_ContentLibrarySpec(a.(*v1alpha2.ContentLibrarySpec), b.(*ContentLibrarySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContentLibraryStatus)(nil), (*ContentLibraryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContentLibraryStatus_To_v1alpha1_ContentLibraryStatus(a.(*v1alpha2.ContentLibraryStatus), b.(*ContentLibraryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.FileInfo)(nil), (*FileInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_FileInfo_To_v1alpha1_FileInfo(a.(*v1alpha2.FileInfo), b.(*FileInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.FileTransferStatus)(nil), (*FileTransferStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_FileTransferStatus_To_v1alpha1_FileTransferStatus(a.(*v1alpha2.FileTransferStatus), b.(*FileTransferStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BaseContentLibrarySpec_To_v1alpha2_BaseContentLibrarySpec(in *BaseContentLibrarySpec, out *v1alpha2.BaseContentLibrarySpec, s conversion.Scope) error {
	// WARNING: in.UUID requires manual conversion: does not exist in peer-type
	out.ResourceNamingStrategy = v1alpha2.ResourceNamingStrategy(in.ResourceNamingStrategy)
	return nil
}

func autoConvert_v1alpha2_BaseContentLibrarySpec_To_v1alpha1_BaseContentLibrarySpec(in *v1alpha2.BaseContentLibrarySpec, out *BaseContentLibrarySpec, s conversion.Scope) error {
	// WARNING: in.ID requires manual conversion: does not exist in peer-type
	// WARNING: in.Type requires manual conversion: does not exist in peer-type
	out.ResourceNamingStrategy = ResourceNamingStrategy(in.ResourceNamingStrategy)
	return nil
}

func autoConvert_v1alpha1_CertificateVerificationInfo_To_v1alpha2_CertificateVerificationInfo(in *CertificateVerificationInfo, out *v1alpha2.CertificateVerificationInfo, s conversion.Scope) error {
	out.Status = v1alpha2.CertVerificationStatus(in.Status)
	out.CertChain = *(*[]string)(unsafe.Pointer(&in.CertChain))
	return nil
}

func autoConvert_v1alpha2_CertificateVerificationInfo_To_v1alpha1_CertificateVerificationInfo(in *v1alpha2.CertificateVerificationInfo, out *CertificateVerificationInfo, s conversion.Scope) error {
	out.Status = CertVerificationStatus(in.Status)
	out.CertChain = *(*[]string)(unsafe.Pointer(&in.CertChain))
	return nil
}

func autoConvert_v1alpha1_Checksum_To_v1alpha2_Checksum(in *Checksum, out *v1alpha2.Checksum, s conversion.Scope) error {
	out.Algorithm = in.Algorithm
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_Checksum_To_v1alpha2_Checksum is an autogenerated conversion function.
func Convert_v1alpha1_Checksum_To_v1alpha2_Checksum(in *Checksum, out *v1alpha2.Checksum, s conversion.Scope) error {
	return autoConvert_v1alpha1_Checksum_To_v1alpha2_Checksum(in, out, s)
}

func autoConvert_v1alpha2_Checksum_To_v1alpha1_Checksum(in *v1alpha2.Checksum, out *Checksum, s conversion.Scope) error {
	out.Algorithm = in.Algorithm
	out.Value = in.Value
	return nil
}

// Convert_v1alpha2_Checksum_To_v1alpha1_Checksum is an autogenerated conversion function.
func Convert_v1alpha2_Checksum_To_v1alpha1_Checksum(in *v1alpha2.Checksum, out *Checksum, s conversion.Scope) error {
	return autoConvert_v1alpha2_Checksum_To_v1alpha1_Checksum(in, out, s)
}

func autoConvert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary(in *ClusterContentLibrary, out *v1alpha2.ClusterContentLibrary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterContentLibrarySpec_To_v1alpha2_ClusterContentLibrarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryStatus_To_v1alpha2_ContentLibraryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary is an autogenerated conversion function.
func Convert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary(in *ClusterContentLibrary, out *v1alpha2.ClusterContentLibrary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary(in, out, s)
}

func autoConvert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary(in *v1alpha2.ClusterContentLibrary, out *ClusterContentLibrary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ClusterContentLibrarySpec_To_v1alpha1_ClusterContentLibrarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryStatus_To_v1alpha1_ContentLibraryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary is an autogenerated conversion function.
func Convert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary(in *v1alpha2.ClusterContentLibrary, out *ClusterContentLibrary, s conversion.Scope) error {
	return autoConvert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary(in, out, s)
}

func autoConvert_v1alpha1_ClusterContentLibraryItem_To_v1alpha2_ClusterContentLibraryItem(in *ClusterContentLibraryItem, out *v1alpha2.ClusterContentLibraryItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContentLibraryItemSpec_To_v1alpha2_ContentLibraryItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryItemStatus_To_v1alpha2_ContentLibraryItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem(in *v1alpha2.ClusterContentLibraryItem, out *ClusterContentLibraryItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ContentLibraryItemSpec_To_v1alpha1_ContentLibraryItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryItemStatus_To_v1alpha1_ContentLibraryItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem is an autogenerated conversion function.
func Convert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem(in *v1alpha2.ClusterContentLibraryItem, out *ClusterContentLibraryItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem(in, out, s)
}

func autoConvert_v1alpha1_ClusterContentLibraryItemList_To_v1alpha2_ClusterContentLibraryItemList(in *ClusterContentLibraryItemList, out *v1alpha2.ClusterContentLibraryItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ClusterContentLibraryItem, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ClusterContentLibraryItem_To_v1alpha2_ClusterContentLibraryItem(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ClusterContentLibraryItemList_To_v1alpha2_ClusterContentLibraryItemList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterContentLibraryItemList_To_v1alpha2_ClusterContentLibraryItemList(in *ClusterContentLibraryItemList, out *v1alpha2.ClusterContentLibraryItemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterContentLibraryItemList_To_v1alpha2_ClusterContentLibraryItemList(in, out, s)
}

func autoConvert_v1alpha2_ClusterContentLibraryItemList_To_v1alpha1_ClusterContentLibraryItemList(in *v1alpha2.ClusterContentLibraryItemList, out *ClusterContentLibraryItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterContentLibraryItem, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ClusterContentLibraryItem_To_v1alpha1_ClusterContentLibraryItem(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ClusterContentLibraryItemList_To_v1alpha1_ClusterContentLibraryItemList is an autogenerated conversion function.
func Convert_v1alpha2_ClusterContentLibraryItemList_To_v1alpha1_ClusterContentLibraryItemList(in *v1alpha2.ClusterContentLibraryItemList, out *ClusterContentLibraryItemList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ClusterContentLibraryItemList_To_v1alpha1_ClusterContentLibraryItemList(in, out, s)
}

func autoConvert_v1alpha1_ClusterContentLibraryList_To_v1alpha2_ClusterContentLibraryList(in *ClusterContentLibraryList, out *v1alpha2.ClusterContentLibraryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ClusterContentLibrary, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ClusterContentLibrary_To_v1alpha2_ClusterContentLibrary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ClusterContentLibraryList_To_v1alpha2_ClusterContentLibraryList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterContentLibraryList_To_v1alpha2_ClusterContentLibraryList(in *ClusterContentLibraryList, out *v1alpha2.ClusterContentLibraryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterContentLibraryList_To_v1alpha2_ClusterContentLibraryList(in, out, s)
}

func autoConvert_v1alpha2_ClusterContentLibraryList_To_v1alpha1_ClusterContentLibraryList(in *v1alpha2.ClusterContentLibraryList, out *ClusterContentLibraryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterContentLibrary, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ClusterContentLibrary_To_v1alpha1_ClusterContentLibrary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ClusterContentLibraryList_To_v1alpha1_ClusterContentLibraryList is an autogenerated conversion function.
func Convert_v1alpha2_ClusterContentLibraryList_To_v1alpha1_ClusterContentLibraryList(in *v1alpha2.ClusterContentLibraryList, out *ClusterContentLibraryList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ClusterContentLibraryList_To_v1alpha1_ClusterContentLibraryList(in, out, s)
}

func autoConvert_v1alpha1_ClusterContentLibrarySpec_To_v1alpha2_ClusterContentLibrarySpec(in *ClusterContentLibrarySpec, out *v1alpha2.ClusterContentLibrarySpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_BaseContentLibrarySpec_To_v1alpha2_BaseContentLibrarySpec(&in.BaseContentLibrarySpec, &out.BaseContentLibrarySpec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ClusterContentLibrarySpec_To_v1alpha1_ClusterContentLibrarySpec(in *v1alpha2.ClusterContentLibrarySpec, out *ClusterContentLibrarySpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_BaseContentLibrarySpec_To_v1alpha1_BaseContentLibrarySpec(&in.BaseContentLibrarySpec, &out.BaseContentLibrarySpec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Condition_To_v1_Condition(in *Condition, out *v1.Condition, s conversion.Scope) error {
	out.Type = string(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	// WARNING: in.Severity requires manual conversion: does not exist in peer-type
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

func autoConvert_v1_Condition_To_v1alpha1_Condition(in *v1.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	// WARNING: in.ObservedGeneration requires manual conversion: does not exist in peer-type
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

func autoConvert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary(in *ContentLibrary, out *v1alpha2.ContentLibrary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContentLibrarySpec_To_v1alpha2_ContentLibrarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryStatus_To_v1alpha2_ContentLibraryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary(in *ContentLibrary, out *v1alpha2.ContentLibrary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary(in, out, s)
}

func autoConvert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary(in *v1alpha2.ContentLibrary, out *ContentLibrary, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ContentLibrarySpec_To_v1alpha1_ContentLibrarySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryStatus_To_v1alpha1_ContentLibraryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary(in *v1alpha2.ContentLibrary, out *ContentLibrary, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItem_To_v1alpha2_ContentLibraryItem(in *ContentLibraryItem, out *v1alpha2.ContentLibraryItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContentLibraryItemSpec_To_v1alpha2_ContentLibraryItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryItemStatus_To_v1alpha2_ContentLibraryItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem(in *v1alpha2.ContentLibraryItem, out *ContentLibraryItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ContentLibraryItemSpec_To_v1alpha1_ContentLibraryItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryItemStatus_To_v1alpha1_ContentLibraryItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem(in *v1alpha2.ContentLibraryItem, out *ContentLibraryItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus(in *ContentLibraryItemFileUploadStatus, out *v1alpha2.ContentLibraryItemFileUploadStatus, s conversion.Scope) error {
	out.SessionUUID = types.UID(in.SessionUUID)
	if in.FileUploads != nil {
		in, out := &in.FileUploads, &out.FileUploads
		*out = make([]v1alpha2.FileTransferStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_FileTransferStatus_To_v1alpha2_FileTransferStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.FileUploads = nil
	}
	return nil
}

// Convert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus(in *ContentLibraryItemFileUploadStatus, out *v1alpha2.ContentLibraryItemFileUploadStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus(in *v1alpha2.ContentLibraryItemFileUploadStatus, out *ContentLibraryItemFileUploadStatus, s conversion.Scope) error {
	out.SessionUUID = types.UID(in.SessionUUID)
	if in.FileUploads != nil {
		in, out := &in.FileUploads, &out.FileUploads
		*out = make([]FileTransferStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_FileTransferStatus_To_v1alpha1_FileTransferStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.FileUploads = nil
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus(in *v1alpha2.ContentLibraryItemFileUploadStatus, out *ContentLibraryItemFileUploadStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest(in *ContentLibraryItemImportRequest, out *v1alpha2.ContentLibraryItemImportRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryItemImportRequestStatus_To_v1alpha2_ContentLibraryItemImportRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest(in *ContentLibraryItemImportRequest, out *v1alpha2.ContentLibraryItemImportRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest(in *v1alpha2.ContentLibraryItemImportRequest, out *ContentLibraryItemImportRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryItemImportRequestStatus_To_v1alpha1_ContentLibraryItemImportRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest(in *v1alpha2.ContentLibraryItemImportRequest, out *ContentLibraryItemImportRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestList_To_v1alpha2_ContentLibraryItemImportRequestList(in *ContentLibraryItemImportRequestList, out *v1alpha2.ContentLibraryItemImportRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ContentLibraryItemImportRequest, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ContentLibraryItemImportRequest_To_v1alpha2_ContentLibraryItemImportRequest(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ContentLibraryItemImportRequestList_To_v1alpha2_ContentLibraryItemImportRequestList is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemImportRequestList_To_v1alpha2_ContentLibraryItemImportRequestList(in *ContentLibraryItemImportRequestList, out *v1alpha2.ContentLibraryItemImportRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemImportRequestList_To_v1alpha2_ContentLibraryItemImportRequestList(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestList_To_v1alpha1_ContentLibraryItemImportRequestList(in *v1alpha2.ContentLibraryItemImportRequestList, out *ContentLibraryItemImportRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentLibraryItemImportRequest, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ContentLibraryItemImportRequest_To_v1alpha1_ContentLibraryItemImportRequest(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryItemImportRequestList_To_v1alpha1_ContentLibraryItemImportRequestList is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemImportRequestList_To_v1alpha1_ContentLibraryItemImportRequestList(in *v1alpha2.ContentLibraryItemImportRequestList, out *ContentLibraryItemImportRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemImportRequestList_To_v1alpha1_ContentLibraryItemImportRequestList(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource(in *ContentLibraryItemImportRequestSource, out *v1alpha2.ContentLibraryItemImportRequestSource, s conversion.Scope) error {
	out.URL = in.URL
	out.SSLCertificate = in.SSLCertificate
	out.Checksum = (*v1alpha2.Checksum)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource(in *ContentLibraryItemImportRequestSource, out *v1alpha2.ContentLibraryItemImportRequestSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource(in *v1alpha2.ContentLibraryItemImportRequestSource, out *ContentLibraryItemImportRequestSource, s conversion.Scope) error {
	out.URL = in.URL
	out.SSLCertificate = in.SSLCertificate
	out.Checksum = (*Checksum)(unsafe.Pointer(in.Checksum))
	return nil
}

// Convert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource(in *v1alpha2.ContentLibraryItemImportRequestSource, out *ContentLibraryItemImportRequestSource, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec(in *ContentLibraryItemImportRequestSpec, out *v1alpha2.ContentLibraryItemImportRequestSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ContentLibraryItemImportRequestSource_To_v1alpha2_ContentLibraryItemImportRequestSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContentLibraryItemImportRequestTarget_To_v1alpha2_ContentLibraryItemImportRequestTarget(&in.Target, &out.Target, s); err != nil {
		return err
	}
	out.TTLSecondsAfterFinished = (*int64)(unsafe.Pointer(in.TTLSecondsAfterFinished))
	return nil
}

// Convert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec(in *ContentLibraryItemImportRequestSpec, out *v1alpha2.ContentLibraryItemImportRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemImportRequestSpec_To_v1alpha2_ContentLibraryItemImportRequestSpec(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec(in *v1alpha2.ContentLibraryItemImportRequestSpec, out *ContentLibraryItemImportRequestSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ContentLibraryItemImportRequestSource_To_v1alpha1_ContentLibraryItemImportRequestSource(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ContentLibraryItemImportRequestTarget_To_v1alpha1_ContentLibraryItemImportRequestTarget(&in.Target, &out.Target, s); err != nil {
		return err
	}
	out.TTLSecondsAfterFinished = (*int64)(unsafe.Pointer(in.TTLSecondsAfterFinished))
	return nil
}

// Convert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec(in *v1alpha2.ContentLibraryItemImportRequestSpec, out *ContentLibraryItemImportRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemImportRequestSpec_To_v1alpha1_ContentLibraryItemImportRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestStatus_To_v1alpha2_ContentLibraryItemImportRequestStatus(in *ContentLibraryItemImportRequestStatus, out *v1alpha2.ContentLibraryItemImportRequestStatus, s conversion.Scope) error {
	// WARNING: in.ItemRef requires manual conversion: does not exist in peer-type
	out.CompletionTime = in.CompletionTime
	out.StartTime = in.StartTime
	if in.FileUploadStatus != nil {
		in, out := &in.FileUploadStatus, &out.FileUploadStatus
		*out = new(v1alpha2.ContentLibraryItemFileUploadStatus)
		if err := Convert_v1alpha1_ContentLibraryItemFileUploadStatus_To_v1alpha2_ContentLibraryItemFileUploadStatus(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.FileUploadStatus = nil
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestStatus_To_v1alpha1_ContentLibraryItemImportRequestStatus(in *v1alpha2.ContentLibraryItemImportRequestStatus, out *ContentLibraryItemImportRequestStatus, s conversion.Scope) error {
	// WARNING: in.ItemName requires manual conversion: does not exist in peer-type
	out.CompletionTime = in.CompletionTime
	out.StartTime = in.StartTime
	if in.FileUploadStatus != nil {
		in, out := &in.FileUploadStatus, &out.FileUploadStatus
		*out = new(ContentLibraryItemFileUploadStatus)
		if err := Convert_v1alpha2_ContentLibraryItemFileUploadStatus_To_v1alpha1_ContentLibraryItemFileUploadStatus(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.FileUploadStatus = nil
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1alpha1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestTarget_To_v1alpha2_ContentLibraryItemImportRequestTarget(in *ContentLibraryItemImportRequestTarget, out *v1alpha2.ContentLibraryItemImportRequestTarget, s conversion.Scope) error {
	if err := Convert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem(&in.Item, &out.Item, s); err != nil {
		return err
	}
	// WARNING: in.Library requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestTarget_To_v1alpha1_ContentLibraryItemImportRequestTarget(in *v1alpha2.ContentLibraryItemImportRequestTarget, out *ContentLibraryItemImportRequestTarget, s conversion.Scope) error {
	if err := Convert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem(&in.Item, &out.Item, s); err != nil {
		return err
	}
	// WARNING: in.LibraryName requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem(in *ContentLibraryItemImportRequestTargetItem, out *v1alpha2.ContentLibraryItemImportRequestTargetItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.Type = v1alpha2.ContentLibraryItemType(in.Type)
	return nil
}

// Convert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem(in *ContentLibraryItemImportRequestTargetItem, out *v1alpha2.ContentLibraryItemImportRequestTargetItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemImportRequestTargetItem_To_v1alpha2_ContentLibraryItemImportRequestTargetItem(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem(in *v1alpha2.ContentLibraryItemImportRequestTargetItem, out *ContentLibraryItemImportRequestTargetItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.Type = ContentLibraryItemType(in.Type)
	return nil
}

// Convert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem(in *v1alpha2.ContentLibraryItemImportRequestTargetItem, out *ContentLibraryItemImportRequestTargetItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemImportRequestTargetItem_To_v1alpha1_ContentLibraryItemImportRequestTargetItem(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemList_To_v1alpha2_ContentLibraryItemList(in *ContentLibraryItemList, out *v1alpha2.ContentLibraryItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ContentLibraryItem, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ContentLibraryItem_To_v1alpha2_ContentLibraryItem(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ContentLibraryItemList_To_v1alpha2_ContentLibraryItemList is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryItemList_To_v1alpha2_ContentLibraryItemList(in *ContentLibraryItemList, out *v1alpha2.ContentLibraryItemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryItemList_To_v1alpha2_ContentLibraryItemList(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryItemList_To_v1alpha1_ContentLibraryItemList(in *v1alpha2.ContentLibraryItemList, out *ContentLibraryItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentLibraryItem, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ContentLibraryItem_To_v1alpha1_ContentLibraryItem(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryItemList_To_v1alpha1_ContentLibraryItemList is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryItemList_To_v1alpha1_ContentLibraryItemList(in *v1alpha2.ContentLibraryItemList, out *ContentLibraryItemList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryItemList_To_v1alpha1_ContentLibraryItemList(in, out, s)
}

func autoConvert_v1alpha1_ContentLibraryItemSpec_To_v1alpha2_ContentLibraryItemSpec(in *ContentLibraryItemSpec, out *v1alpha2.ContentLibraryItemSpec, s conversion.Scope) error {
	// WARNING: in.UUID requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_ContentLibraryItemSpec_To_v1alpha1_ContentLibraryItemSpec(in *v1alpha2.ContentLibraryItemSpec, out *ContentLibraryItemSpec, s conversion.Scope) error {
	// WARNING: in.ID requires manual conversion: does not exist in peer-type
	// WARNING: in.LibraryName requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_ContentLibraryItemStatus_To_v1alpha2_ContentLibraryItemStatus(in *ContentLibraryItemStatus, out *v1alpha2.ContentLibraryItemStatus, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.ContentLibraryRef requires manual conversion: does not exist in peer-type
	out.Description = in.Description
	// WARNING: in.MetadataVersion requires manual conversion: does not exist in peer-type
	out.ContentVersion = in.ContentVersion
	out.Type = v1alpha2.ContentLibraryItemType(in.Type)
	out.SourceID = string(in.SourceID)
	out.SizeInBytes = in.SizeInBytes
	out.Cached = in.Cached
	out.SecurityCompliance = (*bool)(unsafe.Pointer(in.SecurityCompliance))
	if in.CertificateVerificationInfo != nil {
		in, out := &in.CertificateVerificationInfo, &out.CertificateVerificationInfo
		*out = new(v1alpha2.CertificateVerificationInfo)
		if err := Convert_v1alpha1_CertificateVerificationInfo_To_v1alpha2_CertificateVerificationInfo(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CertificateVerificationInfo = nil
	}
	if in.FileInfo != nil {
		in, out := &in.FileInfo, &out.FileInfo
		*out = make([]v1alpha2.FileInfo, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_FileInfo_To_v1alpha2_FileInfo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.FileInfo = nil
	}
	out.CreationTime = in.CreationTime
	out.LastModifiedTime = in.LastModifiedTime
	out.LastSyncTime = in.LastSyncTime
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha2_ContentLibraryItemStatus_To_v1alpha1_ContentLibraryItemStatus(in *v1alpha2.ContentLibraryItemStatus, out *ContentLibraryItemStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	// WARNING: in.Version requires manual conversion: does not exist in peer-type
	out.ContentVersion = in.ContentVersion
	out.Type = ContentLibraryItemType(in.Type)
	out.SourceID = types.UID(in.SourceID)
	out.SizeInBytes = in.SizeInBytes
	out.Cached = in.Cached
	out.SecurityCompliance = (*bool)(unsafe.Pointer(in.SecurityCompliance))
	if in.CertificateVerificationInfo != nil {
		in, out := &in.CertificateVerificationInfo, &out.CertificateVerificationInfo
		*out = new(CertificateVerificationInfo)
		if err := Convert_v1alpha2_CertificateVerificationInfo_To_v1alpha1_CertificateVerificationInfo(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CertificateVerificationInfo = nil
	}
	if in.FileInfo != nil {
		in, out := &in.FileInfo, &out.FileInfo
		*out = make([]FileInfo, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_FileInfo_To_v1alpha1_FileInfo(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.FileInfo = nil
	}
	out.CreationTime = in.CreationTime
	out.LastModifiedTime = in.LastModifiedTime
	out.LastSyncTime = in.LastSyncTime
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1alpha1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha1_ContentLibraryList_To_v1alpha2_ContentLibraryList(in *ContentLibraryList, out *v1alpha2.ContentLibraryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ContentLibrary, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ContentLibrary_To_v1alpha2_ContentLibrary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ContentLibraryList_To_v1alpha2_ContentLibraryList is an autogenerated conversion function.
func Convert_v1alpha1_ContentLibraryList_To_v1alpha2_ContentLibraryList(in *ContentLibraryList, out *v1alpha2.ContentLibraryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContentLibraryList_To_v1alpha2_ContentLibraryList(in, out, s)
}

func autoConvert_v1alpha2_ContentLibraryList_To_v1alpha1_ContentLibraryList(in *v1alpha2.ContentLibraryList, out *ContentLibraryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentLibrary, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ContentLibrary_To_v1alpha1_ContentLibrary(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ContentLibraryList_To_v1alpha1_ContentLibraryList is an autogenerated conversion function.
func Convert_v1alpha2_ContentLibraryList_To_v1alpha1_ContentLibraryList(in *v1alpha2.ContentLibraryList, out *ContentLibraryList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ContentLibraryList_To_v1alpha1_ContentLibraryList(in, out, s)
}

func autoConvert_v1alpha1_ContentLibrarySpec_To_v1alpha2_ContentLibrarySpec(in *ContentLibrarySpec, out *v1alpha2.ContentLibrarySpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_BaseContentLibrarySpec_To_v1alpha2_BaseContentLibrarySpec(&in.BaseContentLibrarySpec, &out.BaseContentLibrarySpec, s); err != nil {
		return err
	}
	// WARNING: in.Writable requires manual conversion: does not exist in peer-type
	out.AllowImport = in.AllowImport
	return nil
}

func autoConvert_v1alpha2_ContentLibrarySpec_To_v1alpha1_ContentLibrarySpec(in *v1alpha2.ContentLibrarySpec, out *ContentLibrarySpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_BaseContentLibrarySpec_To_v1alpha1_BaseContentLibrarySpec(&in.BaseContentLibrarySpec, &out.BaseContentLibrarySpec, s); err != nil {
		return err
	}
	// WARNING: in.StorageClass requires manual conversion: does not exist in peer-type
	// WARNING: in.AllowDelete requires manual conversion: does not exist in peer-type
	out.AllowImport = in.AllowImport
	// WARNING: in.AllowPublish requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_ContentLibraryStatus_To_v1alpha2_ContentLibraryStatus(in *ContentLibraryStatus, out *v1alpha2.ContentLibraryStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	// WARNING: in.Type requires manual conversion: does not exist in peer-type
	// WARNING: in.StorageBacking requires manual conversion: does not exist in peer-type
	out.Version = in.Version
	out.PublishInfo = (*v1alpha2.PublishInfo)(unsafe.Pointer(in.PublishInfo))
	out.SubscriptionInfo = (*v1alpha2.SubscriptionInfo)(unsafe.Pointer(in.SubscriptionInfo))
	out.SecurityPolicyID = in.SecurityPolicyID
	out.State = v1alpha2.State(in.State)
	out.ServerGUID = in.ServerGUID
	out.CreationTime = in.CreationTime
	out.LastModifiedTime = in.LastModifiedTime
	out.LastSyncTime = in.LastSyncTime
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha2_ContentLibraryStatus_To_v1alpha1_ContentLibraryStatus(in *v1alpha2.ContentLibraryStatus, out *ContentLibraryStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	// WARNING: in.StorageBackings requires manual conversion: does not exist in peer-type
	out.Version = in.Version
	out.PublishInfo = (*PublishInfo)(unsafe.Pointer(in.PublishInfo))
	out.SubscriptionInfo = (*SubscriptionInfo)(unsafe.Pointer(in.SubscriptionInfo))
	out.SecurityPolicyID = in.SecurityPolicyID
	out.State = State(in.State)
	out.ServerGUID = in.ServerGUID
	out.CreationTime = in.CreationTime
	out.LastModifiedTime = in.LastModifiedTime
	out.LastSyncTime = in.LastSyncTime
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1alpha1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha1_FileInfo_To_v1alpha2_FileInfo(in *FileInfo, out *v1alpha2.FileInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.SizeInBytes = in.SizeInBytes
	out.Version = in.Version
	out.Cached = in.Cached
	out.StorageURI = in.StorageURI
	return nil
}

func autoConvert_v1alpha2_FileInfo_To_v1alpha1_FileInfo(in *v1alpha2.FileInfo, out *FileInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.SizeInBytes = in.SizeInBytes
	out.Version = in.Version
	out.Cached = in.Cached
	out.StorageURI = in.StorageURI
	return nil
}

func autoConvert_v1alpha1_FileTransferStatus_To_v1alpha2_FileTransferStatus(in *FileTransferStatus, out *v1alpha2.FileTransferStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = v1alpha2.TransferStatus(in.Status)
	out.BytesTransferred = (*int64)(unsafe.Pointer(in.BytesTransferred))
	out.Size = (*int64)(unsafe.Pointer(in.Size))
	out.ErrorMessage = in.ErrorMessage
	return nil
}

func autoConvert_v1alpha2_FileTransferStatus_To_v1alpha1_FileTransferStatus(in *v1alpha2.FileTransferStatus, out *FileTransferStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = TransferStatus(in.Status)
	out.BytesTransferred = (*int64)(unsafe.Pointer(in.BytesTransferred))
	out.Size = (*int64)(unsafe.Pointer(in.Size))
	out.ErrorMessage = in.ErrorMessage
	return nil
}

func autoConvert_v1alpha1_PublishInfo_To_v1alpha2_PublishInfo(in *PublishInfo, out *v1alpha2.PublishInfo, s conversion.Scope) error {
	out.Published = in.Published
	out.URL = in.URL
	return nil
}

// Convert_v1alpha1_PublishInfo_To_v1alpha2_PublishInfo is an autogenerated conversion function.
func Convert_v1alpha1_PublishInfo_To_v1alpha2_PublishInfo(in *PublishInfo, out *v1alpha2.PublishInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_PublishInfo_To_v1alpha2_PublishInfo(in, out, s)
}

func autoConvert_v1alpha2_PublishInfo_To_v1alpha1_PublishInfo(in *v1alpha2.PublishInfo, out *PublishInfo, s conversion.Scope) error {
	out.Published = in.Published
	out.URL = in.URL
	return nil
}

// Convert_v1alpha2_PublishInfo_To_v1alpha1_PublishInfo is an autogenerated conversion function.
func Convert_v1alpha2_PublishInfo_To_v1alpha1_PublishInfo(in *v1alpha2.PublishInfo, out *PublishInfo, s conversion.Scope) error {
	return autoConvert_v1alpha2_PublishInfo_To_v1alpha1_PublishInfo(in, out, s)
}

func autoConvert_v1alpha1_StorageBacking_To_v1alpha2_StorageBacking(in *StorageBacking, out *v1alpha2.StorageBacking, s conversion.Scope) error {
	out.Type = v1alpha2.StorageBackingType(in.Type)
	out.DatastoreID = in.DatastoreID
	return nil
}

// Convert_v1alpha1_StorageBacking_To_v1alpha2_StorageBacking is an autogenerated conversion function.
func Convert_v1alpha1_StorageBacking_To_v1alpha2_StorageBacking(in *StorageBacking, out *v1alpha2.StorageBacking, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageBacking_To_v1alpha2_StorageBacking(in, out, s)
}

func autoConvert_v1alpha2_StorageBacking_To_v1alpha1_StorageBacking(in *v1alpha2.StorageBacking, out *StorageBacking, s conversion.Scope) error {
	out.Type = StorageBackingType(in.Type)
	out.DatastoreID = in.DatastoreID
	return nil
}

// Convert_v1alpha2_StorageBacking_To_v1alpha1_StorageBacking is an autogenerated conversion function.
func Convert_v1alpha2_StorageBacking_To_v1alpha1_StorageBacking(in *v1alpha2.StorageBacking, out *StorageBacking, s conversion.Scope) error {
	return autoConvert_v1alpha2_StorageBacking_To_v1alpha1_StorageBacking(in, out, s)
}

func autoConvert_v1alpha1_SubscriptionInfo_To_v1alpha2_SubscriptionInfo(in *SubscriptionInfo, out *v1alpha2.SubscriptionInfo, s conversion.Scope) error {
	out.URL = in.URL
	out.OnDemand = in.OnDemand
	out.AutomaticSync = in.AutomaticSync
	return nil
}

// Convert_v1alpha1_SubscriptionInfo_To_v1alpha2_SubscriptionInfo is an autogenerated conversion function.
func Convert_v1alpha1_SubscriptionInfo_To_v1alpha2_SubscriptionInfo(in *SubscriptionInfo, out *v1alpha2.SubscriptionInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubscriptionInfo_To_v1alpha2_SubscriptionInfo(in, out, s)
}

func autoConvert_v1alpha2_SubscriptionInfo_To_v1alpha1_SubscriptionInfo(in *v1alpha2.SubscriptionInfo, out *SubscriptionInfo, s conversion.Scope) error {
	out.URL = in.URL
	out.OnDemand = in.OnDemand
	out.AutomaticSync = in.AutomaticSync
	return nil
}

// Convert_v1alpha2_SubscriptionInfo_To_v1alpha1_SubscriptionInfo is an autogenerated conversion function.
func Convert_v1alpha2_SubscriptionInfo_To_v1alpha1_SubscriptionInfo(in *v1alpha2.SubscriptionInfo, out *SubscriptionInfo, s conversion.Scope) error {
	return autoConvert_v1alpha2_SubscriptionInfo_To_v1alpha1_SubscriptionInfo(in, out, s)
}
