name: ci

env:
  # This value is usually commented out, allowing the go-version-file
  # directive to pull the Go version from the go.mod file. However,
  # sometimes we need to explicitly override the Go version, ex. CVEs,
  # when it is not possible to update the go.mod version yet, ex. the
  # internal builds do not yet support that version of Go.
  GO_VERSION: ""

on:
  pull_request:
    branches:
    - main
    - 'release/**'
  push:
    branches:
    - main

jobs:

  verify-go-modules:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Run go mod tidy
      run: make modules
    - name: Verify go modules have not changed
      run: git diff --exit-code
    - name: Run go mod download
      run: make modules-download

  verify-codegen:
    needs:
    - verify-go-modules
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Verify codegen
      run: make verify-codegen

  lint-go:
    needs:
    - verify-go-modules
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Setup the cache for golangci-lint
      uses: actions/cache@v4
      with:
        key: golangci-lint-${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('go.sum', 'hack/tools/go.sum') }}
        path: |
          ~/.cache/golangci-lint
          hack/tools/bin/golangci-lint
    - name: Lint Go
      run: make lint-go-full
